global:
  hosts:
    domain: localhost
    externalIP: 127.0.0.1

  ingress:
    configureCertmanager: false

#certmanager-issuer:
#  email: me@example.com

prometheus:
  install: false
gitlab-runner:
  install: false
certmanager:
  install: false
