# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.box = "debian/bullseye64"

	config.vm.define "ajuncosaS" do |node|
		node.vm.hostname = "ajuncosaS"
		node.vm.network "private_network", ip: "192.168.56.110"
		node.vm.provider "virtualbox" do |v|
			v.name = "ajuncosaS"
			v.memory = 1024
			v.cpus = 1
		end
		node.vm.provision "shell", path: "./scripts/install-server.sh"
	end
end
