# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |v|
		v.memory = 512
		v.cpus = 1
	end

	config.vm.define "ajuncosaS" do |node|
		config.vm.box = "hashicorp/bionic64"

		node.vm.hostname = "ajuncosaS"
		node.vm.network "private_network", ip: "192.168.56.110"

		node.vm.provision "shell", path: "./scripts/install-server.sh"

	end

	config.vm.define "apavelSW" do |node|
		config.vm.box = "hashicorp/bionic64"


		node.vm.hostname = "apavelSW"
		node.vm.network "private_network", ip: "192.168.56.111"

		node.vm.provision "shell", path: "./scripts/install-agent.sh"

	end
end
