# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"
  config.vm.define "ajuncosaS"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ajuncosaS"
    vb.memory = 512
    vb.cpus = 1
  end
end
